[book]
authors = ["Absozero"]
language = "en"
multilingual = false
src = "src"
title = "Cliweather docs"
description = "Docs for a Command line weather app"

[output.html.playground]
editable = true
line-numbers = true

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html]
default-theme = "Ayu"
site-url = "/cliweather/"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/absozero/cliweather"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/absozero/cliweather/blob/docs/{path}"
no-section-label = true

[output.html.search]
enable = true
limit-results = 40
teaser-word-count = 30
expand = true

[build]
build-dir = "docs"
create-missing = true
